// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//import 'firebase_options.dart';

// await Firebase.initializeApp(
//  options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN9TkfDxlst81lLWFhL6NMjGDdAxCwxMA',
    appId: '1:712750490544:web:e717a0cd1c79841164ac75',
    messagingSenderId: '712750490544',
    projectId: 'zag-nights',
    authDomain: 'zag-nights.firebaseapp.com',
    storageBucket: 'zag-nights.appspot.com',
    measurementId: 'G-KF5ZST7N41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCIerzMZHoU49xoy_ba2o8MyNNxzlYZZM',
    appId: '1:712750490544:android:57e6e3fba0faa16964ac75',
    messagingSenderId: '712750490544',
    projectId: 'zag-nights',
    storageBucket: 'zag-nights.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAlk-pcn5XiPYG-bvZps9gYr5vTByEsjs',
    appId: '1:712750490544:ios:6f2a19b6d8e7838064ac75',
    messagingSenderId: '712750490544',
    projectId: 'zag-nights',
    storageBucket: 'zag-nights.appspot.com',
    iosBundleId: 'com.example.zagNights',
  );
}
